-- DodoInspect - Data/Loot.lua
-- Season 2 loot tables, generated by tools/gen_loot.py. Do not hand-edit.
--
-- DATA ONLY, ASCII ONLY. Item, boss and instance names are resolved in
-- game from these IDs (C_Item.GetItemInfo / EJ_GetEncounterInfo /
-- EJ_GetInstanceInfo), so the table carries no translated strings and
-- every client language is covered for free.
--
-- Each entry is a positional array, keyed by itemID:
--   [1] journalInstanceID   [2] journalEncounterID
--   [3] boss position, 1..N in Encounter Journal order. This is NOT the
--       raw DB2 OrderIndex, which is 1-based in one raid and 0-based in
--       the other; the generator renumbers it.
--   [4] primary stat        "STR" "AGI" "INT" "SI" "SA" "AI" "SAI",
--                           or nil for rings and necks, which have none
--   [5] first secondary     stat key, matching Data/StatPriority.lua
--   [6] first secondary value
--   [7] second secondary    nil when the item puts everything in one stat
--   [8] second secondary value
--   [9] 1 when the item carries an on-item effect (cantrip, use effect,
--       proc). Those carry value the stat sort cannot see, so the panel
--       flags them rather than pretending the order is complete.
--
-- Secondary values do NOT share a budget across slots: armor totals about
-- 7000, rings and necks about 17500. Normalise against the item's own
-- total ([6] + [8]), never against a constant.
--
-- Slot and armor type are deliberately absent: GetItemInfoInstant returns
-- them synchronously without needing the item cached.

local _, ns = ...

-- specID -> armor type and primary stat, derived from
-- ChrSpecialization and ItemSpec. Used to filter the
-- candidate list: a plate wearer must not be shown the
-- other plate classes' gear, which armor type alone
-- does not achieve (holy paladin wants Intellect while
-- every warrior wants Strength). Rings, necks and cloaks
-- carry no primary stat and skip this filter entirely.
ns.SpecGear = {
    [62] = { "Cloth", "INT" }, -- Arcane
    [63] = { "Cloth", "INT" }, -- Fire
    [64] = { "Cloth", "INT" }, -- Frost
    [65] = { "Plate", "INT" }, -- Holy
    [66] = { "Plate", "STR" }, -- Protection
    [70] = { "Plate", "STR" }, -- Retribution
    [71] = { "Plate", "STR" }, -- Arms
    [72] = { "Plate", "STR" }, -- Fury
    [73] = { "Plate", "STR" }, -- Protection
    [102] = { "Leather", "INT" }, -- Balance
    [103] = { "Leather", "AGI" }, -- Feral
    [104] = { "Leather", "AGI" }, -- Guardian
    [105] = { "Leather", "INT" }, -- Restoration
    [250] = { "Plate", "STR" }, -- Blood
    [251] = { "Plate", "STR" }, -- Frost
    [252] = { "Plate", "STR" }, -- Unholy
    [253] = { "Mail", "AGI" }, -- Beast Mastery
    [254] = { "Mail", "AGI" }, -- Marksmanship
    [255] = { "Mail", "AGI" }, -- Survival
    [256] = { "Cloth", "INT" }, -- Discipline
    [257] = { "Cloth", "INT" }, -- Holy
    [258] = { "Cloth", "INT" }, -- Shadow
    [259] = { "Leather", "AGI" }, -- Assassination
    [260] = { "Leather", "AGI" }, -- Outlaw
    [261] = { "Leather", "AGI" }, -- Subtlety
    [262] = { "Mail", "INT" }, -- Elemental
    [263] = { "Mail", "AGI" }, -- Enhancement
    [264] = { "Mail", "INT" }, -- Restoration
    [265] = { "Cloth", "INT" }, -- Affliction
    [266] = { "Cloth", "INT" }, -- Demonology
    [267] = { "Cloth", "INT" }, -- Destruction
    [268] = { "Leather", "AGI" }, -- Brewmaster
    [269] = { "Leather", "AGI" }, -- Windwalker
    [270] = { "Leather", "INT" }, -- Mistweaver
    [577] = { "Leather", "AGI" }, -- Havoc
    [581] = { "Leather", "AGI" }, -- Vengeance
    [1467] = { "Mail", "INT" }, -- Devastation
    [1468] = { "Mail", "INT" }, -- Preservation
    [1473] = { "Mail", "INT" }, -- Augmentation
    [1480] = { "Leather", "INT" }, -- Devourer
}

-- specID -> the weapon subclass ids that spec's CLASS is
-- allowed to equip, derived from SkillLine +
-- SkillLineAbility.ClassMask. This answers CAN, never
-- SHOULD: a warrior appears here with daggers and bows.
-- Which of them a spec actually wants is the hand-written
-- weapon shape in GearRank.lua. Subclass ids are Blizzard's
-- (0 axe, 1 2h-axe, 2 bow, 3 gun, 4 mace, 5 2h-mace,
--  6 polearm, 7 sword, 8 2h-sword, 9 warglaive, 10 staff,
--  13 fist, 15 dagger, 18 crossbow, 19 wand).
ns.SpecWeapons = {
    [62] = { [7] = true, [10] = true, [15] = true, [19] = true }, -- Arcane
    [63] = { [7] = true, [10] = true, [15] = true, [19] = true }, -- Fire
    [64] = { [7] = true, [10] = true, [15] = true, [19] = true }, -- Frost
    [65] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true }, -- Holy
    [66] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true }, -- Protection
    [70] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true }, -- Retribution
    [71] = { [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true, [18] = true }, -- Arms
    [72] = { [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true, [18] = true }, -- Fury
    [73] = { [0] = true, [1] = true, [2] = true, [3] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true, [18] = true }, -- Protection
    [102] = { [4] = true, [5] = true, [6] = true, [10] = true, [13] = true, [15] = true }, -- Balance
    [103] = { [4] = true, [5] = true, [6] = true, [10] = true, [13] = true, [15] = true }, -- Feral
    [104] = { [4] = true, [5] = true, [6] = true, [10] = true, [13] = true, [15] = true }, -- Guardian
    [105] = { [4] = true, [5] = true, [6] = true, [10] = true, [13] = true, [15] = true }, -- Restoration
    [250] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true }, -- Blood
    [251] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true }, -- Frost
    [252] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true }, -- Unholy
    [253] = { [0] = true, [1] = true, [2] = true, [3] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true, [18] = true }, -- Beast Mastery
    [254] = { [0] = true, [1] = true, [2] = true, [3] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true, [18] = true }, -- Marksmanship
    [255] = { [0] = true, [1] = true, [2] = true, [3] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true, [18] = true }, -- Survival
    [256] = { [4] = true, [10] = true, [15] = true, [19] = true }, -- Discipline
    [257] = { [4] = true, [10] = true, [15] = true, [19] = true }, -- Holy
    [258] = { [4] = true, [10] = true, [15] = true, [19] = true }, -- Shadow
    [259] = { [0] = true, [2] = true, [3] = true, [4] = true, [7] = true, [13] = true, [15] = true, [18] = true }, -- Assassination
    [260] = { [0] = true, [2] = true, [3] = true, [4] = true, [7] = true, [13] = true, [15] = true, [18] = true }, -- Outlaw
    [261] = { [0] = true, [2] = true, [3] = true, [4] = true, [7] = true, [13] = true, [15] = true, [18] = true }, -- Subtlety
    [262] = { [0] = true, [1] = true, [4] = true, [5] = true, [10] = true, [13] = true, [15] = true }, -- Elemental
    [263] = { [0] = true, [1] = true, [4] = true, [5] = true, [10] = true, [13] = true, [15] = true }, -- Enhancement
    [264] = { [0] = true, [1] = true, [4] = true, [5] = true, [10] = true, [13] = true, [15] = true }, -- Restoration
    [265] = { [7] = true, [10] = true, [15] = true, [19] = true }, -- Affliction
    [266] = { [7] = true, [10] = true, [15] = true, [19] = true }, -- Demonology
    [267] = { [7] = true, [10] = true, [15] = true, [19] = true }, -- Destruction
    [268] = { [0] = true, [4] = true, [6] = true, [7] = true, [10] = true, [13] = true, [15] = true }, -- Brewmaster
    [269] = { [0] = true, [4] = true, [6] = true, [7] = true, [10] = true, [13] = true, [15] = true }, -- Windwalker
    [270] = { [0] = true, [4] = true, [6] = true, [7] = true, [10] = true, [13] = true, [15] = true }, -- Mistweaver
    [577] = { [0] = true, [7] = true, [9] = true, [13] = true, [15] = true }, -- Havoc
    [581] = { [0] = true, [7] = true, [9] = true, [13] = true, [15] = true }, -- Vengeance
    [1467] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true }, -- Devastation
    [1468] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true }, -- Preservation
    [1473] = { [0] = true, [1] = true, [4] = true, [5] = true, [6] = true, [7] = true, [8] = true, [10] = true, [13] = true, [15] = true }, -- Augmentation
    [1480] = { [0] = true, [7] = true, [9] = true, [13] = true, [15] = true }, -- Devourer
}

-- specIDs whose class has shield proficiency. Separate
-- from the table above because a shield is armor, not a
-- weapon subclass, and the off-hand pool needs both.
ns.SpecShield = {
    [65] = true, -- Holy
    [66] = true, -- Protection
    [70] = true, -- Retribution
    [71] = true, -- Arms
    [72] = true, -- Fury
    [73] = true, -- Protection
    [262] = true, -- Elemental
    [263] = true, -- Enhancement
    [264] = true, -- Restoration
}

-- journalInstanceID -> challengeMapID for this season's Mythic+
-- pool. Joined on the MapID that JournalInstance and
-- MapChallengeMode both carry, never hand-written: it restates
-- something the client already knows, so a second copy could only
-- ever drift away from it.
--
-- The challenge map id is the key the Mythic+ side panel needs.
-- C_ChallengeMode.GetMapUIInfo takes it and answers with the icon
-- and the localised name (four languages for free), and
-- C_ChallengeMode.GetMapTable answers WITH these ids -- which makes
-- that API something this table can be checked against at runtime
-- rather than a rival source of the same fact.
--
-- Card labels are NOT here. They are the one hand-written thing in
-- this feature and they are language-shaped, so they live in
-- Locales.lua (ns.DungeonShort, with a cn override). This file
-- stays ids-only and ASCII-only.
--
-- Iterate by SORTED key: pairs() order is unspecified, and eight
-- cards that reshuffle between openings would be a bug nobody could
-- reproduce on demand.
ns.ChallengeMap = {
    [1030] = 250, -- Temple of Sethraliss
    [1041] = 249, -- Kings' Rest
    [1202] = 399, -- Ruby Life Pools
    [1304] = 587, -- Murder Row
    [1309] = 584, -- The Blinding Vale
    [1311] = 586, -- Den of Nalorakk
    [1313] = 585, -- Voidscar Arena
    [1322] = 588, -- Altar of Fangs
}

ns.LootMeta = {
    build = "12.1.0.69299",
    date = "2026-08-22",
    raids = { [1317] = true, [1320] = true },
    dungeons = { [1030] = true, [1041] = true, [1202] = true, [1304] = true, [1309] = true, [1311] = true, [1313] = true, [1322] = true },
}

ns.LootData = {

    -- The Tidebound Grotto
    [268199] = { 1317, 2849, 1, "AGI", "crit", 4751, "versatility", 2249, nil },
    [268217] = { 1317, 2849, 1, "AI", "mastery", 4848, "crit", 2152, nil },
    [268221] = { 1317, 2849, 1, "INT", "crit", 4677, "mastery", 2323, nil },
    [268226] = { 1317, 2849, 1, "SI", "crit", 4949, "mastery", 2051, nil },
    [268232] = { 1317, 2849, 1, "INT", "crit", 4951, "versatility", 2049, nil },
    [268238] = { 1317, 2849, 1, "AI", "crit", 4557, "haste", 2443, nil },
    [268244] = { 1317, 2849, 1, "SI", "haste", 4942, "versatility", 2058, nil },
    [268247] = { 1317, 2849, 1, "AI", "haste", 4598, "versatility", 2402, nil },
    [268262] = { 1317, 2849, 1, "SI", "mastery", 4696, "haste", 2304, nil },
    [268263] = { 1317, 2849, 1, "INT", "crit", 4710, "mastery", 2290, nil },
    [268266] = { 1317, 2849, 1, nil, "haste", 13650, "versatility", 3850, nil },
    [270167] = { 1317, 2849, 1, nil, "haste", 6666, nil, nil, 1 },

    -- The Venomous Abyss
    [268196] = { 1320, 2894, 3, "SI", "haste", 4698, "crit", 2302, nil },
    [268197] = { 1320, 2874, 2, "INT", "mastery", 4773, "haste", 2227, nil },
    [268198] = { 1320, 2874, 2, "STR", "crit", 4781, "haste", 2219, nil },
    [268200] = { 1320, 2894, 3, "AGI", "haste", 4851, "mastery", 2149, nil },
    [268201] = { 1320, 2871, 5, "AI", "mastery", 4854, "crit", 2146, nil },
    [268202] = { 1320, 2895, 8, "STR", "haste", 7000, nil, nil, nil },
    [268203] = { 1320, 2888, 1, "INT", "mastery", 4911, "crit", 2089, nil },
    [268204] = { 1320, 2874, 2, "AGI", "haste", 4913, "versatility", 2087, nil },
    [268205] = { 1320, 2882, 4, "INT", "mastery", 4801, "haste", 2199, nil },
    [268206] = { 1320, 2871, 5, "AGI", "crit", 4843, "mastery", 2157, nil },
    [268207] = { 1320, 2895, 8, "AGI", "crit", 7000, nil, nil, nil },
    [268208] = { 1320, 2888, 1, "STR", "mastery", 4591, "crit", 2409, nil },
    [268209] = { 1320, 2883, 7, "SA", "mastery", 4900, "haste", 2100, 1 },
    [268210] = { 1320, 2894, 3, "INT", "mastery", 4893, "crit", 2107, nil },
    [268211] = { 1320, 2883, 7, "INT", "haste", 4765, "mastery", 2235, nil },
    [268213] = { 1320, 2883, 7, "SA", "crit", 4950, "mastery", 2050, 1 },
    [268214] = { 1320, 2882, 4, "STR", "haste", 4650, "mastery", 2350, nil },
    [268215] = { 1320, 2895, 8, "AGI", "mastery", 7000, nil, nil, nil },
    [268216] = { 1320, 2888, 1, "AI", "crit", 4841, "versatility", 2159, nil },
    [268218] = { 1320, 2888, 1, "INT", "crit", 4852, "mastery", 2148, nil },
    [268219] = { 1320, 2874, 2, "AI", "mastery", 4625, "versatility", 2375, nil },
    [268220] = { 1320, 2887, 6, "SI", "crit", 4657, "haste", 2343, nil },
    [268222] = { 1320, 2883, 7, "SI", "haste", 4996, "mastery", 2004, nil },
    [268223] = { 1320, 2887, 6, "AI", "haste", 4712, "crit", 2288, nil },
    [268224] = { 1320, 2874, 2, "SI", "haste", 4736, "mastery", 2264, nil },
    [268225] = { 1320, 2883, 7, "AI", "mastery", 4800, "haste", 2200, nil },
    [268227] = { 1320, 2894, 3, "AI", "crit", 4985, "mastery", 2015, nil },
    [268228] = { 1320, 2874, 2, "INT", "mastery", 4574, "crit", 2426, nil },
    [268229] = { 1320, 2888, 1, "SI", "haste", 4885, "crit", 2115, nil },
    [268230] = { 1320, 2888, 1, "AI", "crit", 4755, "mastery", 2245, nil },
    [268231] = { 1320, 2883, 7, "AI", "mastery", 4859, "crit", 2141, nil },
    [268233] = { 1320, 2871, 5, "AI", "mastery", 4838, "haste", 2162, nil },
    [268234] = { 1320, 2871, 5, "AI", "mastery", 4761, "crit", 2239, nil },
    [268235] = { 1320, 2888, 1, "AI", "haste", 4856, "mastery", 2144, nil },
    [268236] = { 1320, 2888, 1, "INT", "mastery", 4755, "versatility", 2245, nil },
    [268237] = { 1320, 2883, 7, "AI", "haste", 4839, "mastery", 2161, nil },
    [268239] = { 1320, 2894, 3, "SI", "mastery", 4869, "crit", 2131, nil },
    [268240] = { 1320, 2888, 1, "AI", "crit", 4595, "haste", 2405, nil },
    [268241] = { 1320, 2887, 6, "INT", "haste", 4967, "versatility", 2033, nil },
    [268242] = { 1320, 2894, 3, "INT", "haste", 4997, "crit", 2003, nil },
    [268243] = { 1320, 2883, 7, "INT", "haste", 4918, "crit", 2082, nil },
    [268245] = { 1320, 2888, 1, "SI", "crit", 4883, "haste", 2117, nil },
    [268246] = { 1320, 2882, 4, "AI", "crit", 4605, "mastery", 2395, nil },
    [268248] = { 1320, 2888, 1, "SAI", "crit", 4857, "versatility", 2143, nil },
    [268249] = { 1320, 2882, 4, nil, "mastery", 14350, "crit", 3150, 1 },
    [268250] = { 1320, 2874, 2, nil, "haste", 13400, "crit", 4100, 1 },
    [268251] = { 1320, 2887, 6, nil, "mastery", 14850, "haste", 2650, 1 },
    [268252] = { 1320, 2871, 5, nil, "crit", 14600, "haste", 2900, 1 },
    [268253] = { 1320, 2883, 7, "SAI", "mastery", 4941, "haste", 2059, nil },
    [268254] = { 1320, 2882, 4, "AI", "mastery", 4802, "haste", 2198, nil },
    [268255] = { 1320, 2883, 7, "INT", "haste", 4698, "mastery", 2302, nil },
    [268256] = { 1320, 2883, 7, "AI", "mastery", 4803, "haste", 2197, nil },
    [268257] = { 1320, 2871, 5, "INT", "haste", 4744, "mastery", 2256, nil },
    [268258] = { 1320, 2894, 3, "AI", "crit", 4682, "mastery", 2318, nil },
    [268259] = { 1320, 2883, 7, "SI", "crit", 4932, "mastery", 2068, nil },
    [268260] = { 1320, 2882, 4, "SI", "mastery", 4818, "haste", 2182, nil },
    [268261] = { 1320, 2887, 6, "AI", "crit", 4856, "haste", 2144, nil },
    [268264] = { 1320, 2887, 6, "AGI", "mastery", 4611, "crit", 2389, nil },
    [268265] = { 1320, 2895, 8, nil, "crit", 17500, nil, nil, 1 },
    [270160] = { 1320, 2894, 3, "SA", nil, nil, nil, nil, 1 },
    [270161] = { 1320, 2882, 4, "INT", nil, nil, nil, nil, 1 },
    [270162] = { 1320, 2888, 1, "INT", nil, nil, nil, nil, 1 },
    [270163] = { 1320, 2871, 5, "STR", nil, nil, nil, nil, 1 },
    [270164] = { 1320, 2894, 3, "SAI", nil, nil, nil, nil, 1 },
    [270165] = { 1320, 2874, 2, "SA", nil, nil, nil, nil, 1 },
    [270166] = { 1320, 2882, 4, "AGI", nil, nil, nil, nil, 1 },
    [270168] = { 1320, 2895, 8, nil, "mastery", 6666, nil, nil, 1 },
    [270169] = { 1320, 2883, 7, nil, "haste", 6666, nil, nil, 1 },
    [270170] = { 1320, 2887, 6, "INT", nil, nil, nil, nil, 1 },
    [270171] = { 1320, 2887, 6, nil, "crit", 6666, nil, nil, 1 },
    [270173] = { 1320, 2883, 7, "SA", nil, nil, nil, nil, 1 },
    [270174] = { 1320, 2871, 5, nil, "mastery", 6666, nil, nil, 1 },
    [270175] = { 1320, 2895, 8, nil, "crit", 6666, nil, nil, 1 },
    [270930] = { 1320, 2888, 1, "AGI", "haste", 4854, "crit", 2146, nil },
    [271092] = { 1320, 2895, 8, "INT", "haste", 7000, nil, nil, 1 },
    [271093] = { 1320, 2895, 8, "AGI", "crit", 7000, nil, nil, 1 },
    [271874] = { 1320, 2895, 8, "INT", "mastery", 7000, nil, nil, nil },
    [271875] = { 1320, 2895, 8, "AI", "haste", 7000, nil, nil, nil },
    [271876] = { 1320, 2895, 8, "AI", "crit", 7000, nil, nil, nil },
    [271878] = { 1320, 2895, 8, "SI", "mastery", 7000, nil, nil, nil },

    -- Temple of Sethraliss
    [158366] = { 1030, 2144, 3, nil, "crit", 10000, "mastery", 7500, nil },
    [158367] = { 1030, 2143, 2, "STR", nil, nil, nil, nil, 1 },
    [158368] = { 1030, 2145, 4, "INT", nil, nil, nil, nil, 1 },
    [158369] = { 1030, 2144, 3, "INT", "haste", 4100, "versatility", 2900, nil },
    [158370] = { 1030, 2142, 1, "AGI", "haste", 4250, "crit", 2750, nil },
    [158373] = { 1030, 2145, 4, "STR", "crit", 3950, "haste", 3050, nil },
    [158374] = { 1030, 2144, 3, "AGI", nil, nil, nil, nil, 1 },
    [158714] = { 1030, 2143, 2, "AGI", "versatility", 4100, "mastery", 2900, nil },
    [159247] = { 1030, 2144, 3, "INT", "crit", 4700, "haste", 2300, nil },
    [159254] = { 1030, 2145, 4, "INT", nil, nil, nil, nil, nil },
    [159255] = { 1030, 2143, 2, "INT", "mastery", 4100, "versatility", 2900, nil },
    [159257] = { 1030, 2145, 4, "INT", nil, nil, nil, nil, nil },
    [159259] = { 1030, 2142, 1, "INT", "crit", 4250, "haste", 2750, nil },
    [159263] = { 1030, 2142, 1, "INT", "crit", 4100, "versatility", 2900, nil },
    [159317] = { 1030, 2142, 1, "AI", "mastery", 4250, "haste", 2750, nil },
    [159318] = { 1030, 2145, 4, "AI", nil, nil, nil, nil, nil },
    [159327] = { 1030, 2143, 2, "AI", "crit", 4100, "mastery", 2900, nil },
    [159329] = { 1030, 2142, 1, "AI", "mastery", 3800, "versatility", 3200, nil },
    [159337] = { 1030, 2145, 4, "AI", "mastery", 3800, "versatility", 3200, nil },
    [159370] = { 1030, 2145, 4, "AI", nil, nil, nil, nil, nil },
    [159374] = { 1030, 2145, 4, "AI", nil, nil, nil, nil, nil },
    [159375] = { 1030, 2143, 2, "AI", "crit", 4100, "haste", 2900, nil },
    [159380] = { 1030, 2142, 1, "AI", "crit", 4250, "haste", 2750, nil },
    [159388] = { 1030, 2142, 1, "AI", "mastery", 3950, "crit", 3050, nil },
    [159424] = { 1030, 2145, 4, "SI", nil, nil, nil, nil, nil },
    [159425] = { 1030, 2142, 1, "SI", "versatility", 4100, "haste", 2900, nil },
    [159435] = { 1030, 2142, 1, "SI", "versatility", 4400, "crit", 2600, nil },
    [159437] = { 1030, 2143, 2, "SI", "haste", 4250, "mastery", 2750, nil },
    [159439] = { 1030, 2145, 4, "SI", nil, nil, nil, nil, nil },
    [159442] = { 1030, 2144, 3, "SI", "versatility", 4400, "mastery", 2600, nil },
    [159636] = { 1030, 2142, 1, "INT", "haste", 4100, "mastery", 2900, nil },
    [159637] = { 1030, 2143, 2, "AGI", "crit", 3950, "haste", 3050, nil },
    [159664] = { 1030, 2144, 3, "SI", "versatility", 3800, "crit", 3200, nil },
    [162544] = { 1030, 2143, 2, nil, "mastery", 11000, "versatility", 6500, nil },
    [239031] = { 1030, 2145, 4, "INT", "haste", 3600, "crit", 3400, nil },
    [239032] = { 1030, 2145, 4, "INT", "mastery", 3950, "crit", 3050, nil },
    [239033] = { 1030, 2145, 4, "AI", "crit", 4100, "haste", 2900, nil },
    [239034] = { 1030, 2145, 4, "AI", "versatility", 4700, "mastery", 2300, nil },
    [239035] = { 1030, 2145, 4, "AI", "mastery", 4250, "crit", 2750, nil },
    [239036] = { 1030, 2145, 4, "SI", "mastery", 4250, "crit", 2750, nil },
    [239037] = { 1030, 2145, 4, "SI", "haste", 4700, "crit", 2300, nil },

    -- Kings' Rest
    [158344] = { 1041, 2172, 4, "INT", nil, nil, nil, nil, nil },
    [158355] = { 1041, 2172, 4, "AI", nil, nil, nil, nil, nil },
    [159136] = { 1041, 2170, 3, "AGI", "haste", 3650, "mastery", 3350, nil },
    [159137] = { 1041, 2165, 1, "INT", "versatility", 3950, "haste", 3050, nil },
    [159234] = { 1041, 2165, 1, "INT", "crit", 3950, "mastery", 3050, nil },
    [159236] = { 1041, 2172, 4, "INT", nil, nil, nil, nil, nil },
    [159243] = { 1041, 2170, 3, "INT", "versatility", 4550, "haste", 2450, nil },
    [159288] = { 1041, 2170, 3, "SAI", "versatility", 3800, "mastery", 3200, 1 },
    [159300] = { 1041, 2170, 3, "AI", "crit", 4400, "versatility", 2600, nil },
    [159301] = { 1041, 2172, 4, "AI", "crit", 3950, "haste", 3050, nil },
    [159303] = { 1041, 2172, 4, "AI", nil, nil, nil, nil, nil },
    [159304] = { 1041, 2165, 1, "AI", "versatility", 3950, "mastery", 3050, nil },
    [159312] = { 1041, 2171, 2, "AI", "crit", 4250, "mastery", 2750, nil },
    [159313] = { 1041, 2165, 1, "AI", "versatility", 4100, "haste", 2900, nil },
    [159368] = { 1041, 2172, 4, "AI", nil, nil, nil, nil, nil },
    [159369] = { 1041, 2165, 1, "AI", "versatility", 3950, "haste", 3050, nil },
    [159371] = { 1041, 2170, 3, "AI", "versatility", 4100, "mastery", 2900, nil },
    [159409] = { 1041, 2171, 2, "SI", "crit", 4250, "haste", 2750, nil },
    [159412] = { 1041, 2165, 1, "SI", "versatility", 4100, "crit", 2900, nil },
    [159413] = { 1041, 2165, 1, "SI", "mastery", 4700, "crit", 2300, nil },
    [159418] = { 1041, 2170, 3, "SI", "haste", 4400, "mastery", 2600, nil },
    [159422] = { 1041, 2172, 4, "SI", nil, nil, nil, nil, nil },
    [159423] = { 1041, 2172, 4, "SI", nil, nil, nil, nil, nil },
    [159459] = { 1041, 2171, 2, nil, "haste", 11500, "versatility", 6000, nil },
    [159617] = { 1041, 2165, 1, "AGI", nil, nil, nil, nil, 1 },
    [159618] = { 1041, 2171, 2, "SA", nil, nil, nil, nil, 1 },
    [159642] = { 1041, 2171, 2, "AGI", "crit", 3950, "mastery", 3050, nil },
    [159643] = { 1041, 2170, 3, "AGI", "haste", 4100, "mastery", 2900, nil },
    [159644] = { 1041, 2172, 4, "STR", nil, nil, nil, nil, 1 },
    [159645] = { 1041, 2172, 4, "AGI", "mastery", 4100, "crit", 2900, nil },
    [159667] = { 1041, 2171, 2, "INT", "haste", 4250, "versatility", 2750, nil },
    [160213] = { 1041, 2171, 2, "AI", "mastery", 3950, "haste", 3050, nil },
    [160216] = { 1041, 2170, 3, "INT", "crit", 4100, "mastery", 2900, nil },
    [239045] = { 1041, 2172, 4, "INT", "mastery", 4600, "haste", 2400, nil },
    [239046] = { 1041, 2172, 4, "AI", "crit", 4550, "versatility", 2450, nil },
    [239047] = { 1041, 2172, 4, "INT", "versatility", 3950, "crit", 3050, nil },
    [239048] = { 1041, 2172, 4, "AI", "crit", 3950, "mastery", 3050, nil },
    [239049] = { 1041, 2172, 4, "AI", "haste", 3650, "crit", 3350, nil },
    [239050] = { 1041, 2172, 4, "SI", "versatility", 4100, "haste", 2900, nil },
    [239051] = { 1041, 2172, 4, "SI", "versatility", 3950, "mastery", 3050, nil },
    [273649] = { 1041, 2172, 4, "INT", nil, nil, nil, nil, 1 },

    -- Ruby Life Pools
    [193691] = { 1202, 2503, 3, "INT", "haste", 4400, "mastery", 2600, nil },
    [193728] = { 1202, 2488, 1, "SI", "versatility", 4550, "mastery", 2450, nil },
    [193748] = { 1202, 2503, 3, nil, "crit", 6666, nil, nil, 1 },
    [193750] = { 1202, 2503, 3, "INT", "mastery", 4550, "crit", 2450, nil },
    [193751] = { 1202, 2503, 3, "AI", "versatility", 4400, "crit", 2600, nil },
    [193752] = { 1202, 2503, 3, "AI", "mastery", 4100, "crit", 2900, nil },
    [193753] = { 1202, 2503, 3, "SI", "mastery", 4400, "haste", 2600, nil },
    [193754] = { 1202, 2503, 3, "SI", "versatility", 4250, "mastery", 2750, nil },
    [193755] = { 1202, 2503, 3, "STR", "haste", 4400, "crit", 2600, nil },
    [193756] = { 1202, 2503, 3, "AGI", "versatility", 4250, "haste", 2750, nil },
    [193757] = { 1202, 2488, 1, "SAI", nil, nil, nil, nil, 1 },
    [193758] = { 1202, 2488, 1, "AI", "crit", 4100, "versatility", 2900, nil },
    [193759] = { 1202, 2488, 1, "AI", "versatility", 4250, "haste", 2750, nil },
    [193761] = { 1202, 2488, 1, "INT", "crit", 4250, "mastery", 2750, nil },
    [193762] = { 1202, 2485, 2, nil, "haste", 6666, nil, nil, 1 },
    [193763] = { 1202, 2485, 2, "SAI", "haste", 4400, "crit", 2600, nil },
    [193764] = { 1202, 2485, 2, "AI", "mastery", 4250, "versatility", 2750, nil },
    [193765] = { 1202, 2485, 2, "AI", "mastery", 4400, "versatility", 2600, nil },
    [193766] = { 1202, 2485, 2, "INT", "crit", 4550, "versatility", 2450, nil },
    [193767] = { 1202, 2485, 2, "AGI", "crit", 4400, "haste", 2600, nil },

    -- Murder Row
    [250215] = { 1304, 2680, 2, "AI", nil, nil, nil, nil, 1 },
    [250228] = { 1304, 2681, 3, "SA", nil, nil, nil, nil, 1 },
    [250243] = { 1304, 2679, 1, "SA", nil, nil, nil, nil, 1 },
    [250255] = { 1304, 2682, 4, "INT", nil, nil, nil, nil, 1 },
    [251123] = { 1304, 2679, 1, "INT", "crit", 4250, "haste", 2750, nil },
    [251124] = { 1304, 2679, 1, "AI", "crit", 4550, "haste", 2450, nil },
    [251125] = { 1304, 2679, 1, "AI", "versatility", 4550, "crit", 2450, nil },
    [251126] = { 1304, 2679, 1, "SI", "mastery", 4400, "crit", 2600, nil },
    [251127] = { 1304, 2679, 1, "INT", "haste", 4250, "crit", 2750, nil },
    [251128] = { 1304, 2680, 2, "AGI", "crit", 4100, "mastery", 2900, nil },
    [251129] = { 1304, 2680, 2, "INT", "mastery", 4400, "versatility", 2600, nil },
    [251130] = { 1304, 2680, 2, "AI", "crit", 4100, "mastery", 2900, nil },
    [251131] = { 1304, 2680, 2, "AI", "versatility", 4100, "crit", 2900, nil },
    [251132] = { 1304, 2680, 2, "SAI", "crit", 4100, "mastery", 2900, nil },
    [251133] = { 1304, 2680, 2, "SI", "haste", 4250, "crit", 2750, nil },
    [251134] = { 1304, 2681, 3, "STR", "crit", 4100, "haste", 2900, nil },
    [251135] = { 1304, 2681, 3, "AI", "haste", 4400, "crit", 2600, nil },
    [251136] = { 1304, 2681, 3, nil, "crit", 10750, "mastery", 6750, nil },
    [251137] = { 1304, 2681, 3, "INT", "mastery", 4400, "haste", 2600, nil },
    [251138] = { 1304, 2682, 4, "SI", "haste", 4400, "mastery", 2600, nil },
    [251139] = { 1304, 2682, 4, "INT", "haste", 4550, "crit", 2450, nil },
    [251140] = { 1304, 2682, 4, "AI", "haste", 4100, "mastery", 2900, nil },
    [251141] = { 1304, 2682, 4, "AI", "haste", 4250, "versatility", 2750, nil },
    [251142] = { 1304, 2682, 4, nil, "mastery", 12000, "haste", 5500, nil },
    [258045] = { 1304, 2682, 4, nil, nil, nil, nil, nil, nil },
    [271680] = { 1304, 2679, 1, "AGI", "crit", 4550, "versatility", 2450, nil },

    -- The Blinding Vale
    [250214] = { 1309, 2771, 3, "AI", nil, nil, nil, nil, 1 },
    [250238] = { 1309, 2770, 2, "STR", nil, nil, nil, nil, 1 },
    [250254] = { 1309, 2769, 1, "INT", nil, nil, nil, nil, 1 },
    [250259] = { 1309, 2772, 4, "SAI", nil, nil, nil, nil, 1 },
    [251165] = { 1309, 2771, 3, "AI", "crit", 4250, "versatility", 2750, nil },
    [251180] = { 1309, 2769, 1, "AGI", "mastery", 4250, "haste", 2750, nil },
    [251181] = { 1309, 2769, 1, "STR", "haste", 4100, "versatility", 2900, nil },
    [251182] = { 1309, 2769, 1, "SI", "crit", 4250, "versatility", 2750, nil },
    [251183] = { 1309, 2769, 1, "AI", "crit", 4550, "mastery", 2450, nil },
    [251184] = { 1309, 2769, 1, "AI", "haste", 4400, "versatility", 2600, nil },
    [251185] = { 1309, 2769, 1, "INT", "mastery", 4100, "haste", 2900, nil },
    [251186] = { 1309, 2770, 2, "AGI", "mastery", 4400, "crit", 2600, nil },
    [251187] = { 1309, 2770, 2, "AGI", "versatility", 4100, "crit", 2900, nil },
    [251188] = { 1309, 2770, 2, "INT", "haste", 4400, "mastery", 2600, nil },
    [251189] = { 1309, 2770, 2, "AI", "versatility", 4400, "crit", 2600, nil },
    [251190] = { 1309, 2770, 2, "SAI", "haste", 4550, "mastery", 2450, nil },
    [251191] = { 1309, 2771, 3, "INT", "mastery", 4100, "haste", 2900, nil },
    [251192] = { 1309, 2771, 3, "AGI", "crit", 4550, "versatility", 2450, nil },
    [251193] = { 1309, 2771, 3, "SI", "haste", 4400, "versatility", 2600, nil },
    [251194] = { 1309, 2771, 3, nil, "mastery", 11750, "versatility", 5750, nil },
    [251195] = { 1309, 2772, 4, "STR", "haste", 4100, "crit", 2900, nil },
    [251196] = { 1309, 2772, 4, "SI", "crit", 4250, "versatility", 2750, nil },
    [251197] = { 1309, 2772, 4, "SI", "mastery", 4550, "versatility", 2450, nil },
    [251198] = { 1309, 2772, 4, "AI", "versatility", 4400, "mastery", 2600, nil },
    [251199] = { 1309, 2772, 4, "INT", "mastery", 4400, "crit", 2600, nil },
    [251200] = { 1309, 2772, 4, "AI", "haste", 4400, "crit", 2600, nil },

    -- Den of Nalorakk
    [250229] = { 1311, 2778, 3, nil, "crit", 6666, nil, nil, 1 },
    [250244] = { 1311, 2777, 2, nil, nil, nil, nil, nil, 1 },
    [250248] = { 1311, 2776, 1, "INT", nil, nil, nil, nil, 1 },
    [251143] = { 1311, 2776, 1, "AGI", "haste", 4100, "versatility", 2900, nil },
    [251144] = { 1311, 2776, 1, "SI", "mastery", 4250, "versatility", 2750, nil },
    [251145] = { 1311, 2776, 1, "AI", "haste", 4100, "versatility", 2900, nil },
    [251146] = { 1311, 2776, 1, "AI", "versatility", 4100, "crit", 2900, nil },
    [251147] = { 1311, 2776, 1, "INT", "mastery", 4250, "versatility", 2750, nil },
    [251148] = { 1311, 2776, 1, nil, "versatility", 10500, "crit", 7000, nil },
    [251149] = { 1311, 2777, 2, "AGI", "mastery", 4100, "haste", 2900, nil },
    [251150] = { 1311, 2777, 2, "SI", "haste", 4400, "mastery", 2600, nil },
    [251151] = { 1311, 2777, 2, "SI", "crit", 4550, "mastery", 2450, nil },
    [251152] = { 1311, 2777, 2, "AI", "haste", 4100, "versatility", 2900, nil },
    [251153] = { 1311, 2777, 2, "AI", "haste", 4400, "crit", 2600, nil },
    [251154] = { 1311, 2777, 2, "INT", "crit", 4400, "mastery", 2600, nil },
    [251155] = { 1311, 2777, 2, "AI", "crit", 4400, "mastery", 2600, nil },
    [251156] = { 1311, 2778, 3, "INT", "haste", 4400, "versatility", 2600, nil },
    [251158] = { 1311, 2778, 3, "AI", "versatility", 4100, "haste", 2900, nil },
    [251159] = { 1311, 2778, 3, "AI", "mastery", 4400, "haste", 2600, nil },
    [251160] = { 1311, 2778, 3, "INT", "haste", 4400, "crit", 2600, nil },
    [251173] = { 1311, 2778, 3, nil, "haste", 11500, "crit", 6000, nil },
    [251214] = { 1311, 2778, 3, "SI", "haste", 4250, "crit", 2750, nil },
    [271681] = { 1311, 2777, 2, "INT", "mastery", 4100, "crit", 2900, nil },

    -- Voidscar Arena
    [250224] = { 1313, 2793, 3, nil, nil, nil, nil, nil, 1 },
    [250225] = { 1313, 2791, 1, "AGI", nil, nil, nil, nil, 1 },
    [250245] = { 1313, 2792, 2, "SA", nil, nil, nil, nil, 1 },
    [251218] = { 1313, 2791, 1, "STR", "haste", 4100, "mastery", 2900, nil },
    [251219] = { 1313, 2791, 1, "INT", "haste", 4100, "crit", 2900, nil },
    [251220] = { 1313, 2791, 1, "AI", "haste", 4400, "mastery", 2600, nil },
    [251221] = { 1313, 2791, 1, "SI", "versatility", 4250, "mastery", 2750, nil },
    [251222] = { 1313, 2791, 1, "INT", "haste", 4400, "crit", 2600, nil },
    [251223] = { 1313, 2791, 1, "AI", "crit", 4400, "haste", 2600, nil },
    [251224] = { 1313, 2792, 2, "AGI", "mastery", 4550, "haste", 2450, nil },
    [251225] = { 1313, 2792, 2, "INT", "mastery", 4100, "versatility", 2900, nil },
    [251226] = { 1313, 2792, 2, "AI", "crit", 4100, "versatility", 2900, nil },
    [251227] = { 1313, 2792, 2, "INT", "versatility", 4100, "mastery", 2900, nil },
    [251228] = { 1313, 2792, 2, "AI", "haste", 4250, "mastery", 2750, nil },
    [251229] = { 1313, 2792, 2, "SI", "crit", 4550, "mastery", 2450, nil },
    [251230] = { 1313, 2793, 3, "STR", "versatility", 4250, "mastery", 2750, nil },
    [251231] = { 1313, 2793, 3, "AI", "crit", 4100, "haste", 2900, nil },
    [251232] = { 1313, 2793, 3, "INT", "haste", 4250, "mastery", 2750, nil },
    [251233] = { 1313, 2793, 3, "AI", "crit", 4400, "haste", 2600, nil },
    [251234] = { 1313, 2793, 3, nil, "crit", 11250, "mastery", 6250, nil },
    [251235] = { 1313, 2793, 3, "AI", "versatility", 4550, "mastery", 2450, nil },
    [252258] = { 1313, 2792, 2, nil, "haste", 12000, "mastery", 5500, nil },

    -- Altar of Fangs
    [273773] = { 1322, 2880, 3, "INT", "mastery", 3800, "crit", 3200, nil },
    [273774] = { 1322, 2879, 2, "AI", "crit", 4100, "versatility", 2900, nil },
    [273775] = { 1322, 2878, 1, "AI", "mastery", 3800, "versatility", 3200, nil },
    [273776] = { 1322, 2880, 3, "SI", "crit", 3750, "haste", 3250, nil },
    [273777] = { 1322, 2878, 1, "SI", "haste", 3650, "versatility", 3350, nil },
    [273778] = { 1322, 2880, 3, "INT", "haste", 3900, "mastery", 3100, 1 },
    [273779] = { 1322, 2879, 2, "INT", "crit", 3950, "haste", 3050, nil },
    [273780] = { 1322, 2878, 1, "INT", "mastery", 3700, "crit", 3300, nil },
    [273781] = { 1322, 2879, 2, nil, "crit", 9950, "haste", 7550, nil },
    [273782] = { 1322, 2879, 2, "STR", "crit", 3850, "haste", 3150, nil },
    [273783] = { 1322, 2879, 2, "AGI", "haste", 4050, "mastery", 2950, nil },
    [273784] = { 1322, 2880, 3, "AGI", "haste", 4000, "mastery", 3000, nil },
    [273785] = { 1322, 2878, 1, "INT", "haste", 3650, "mastery", 3350, nil },
    [273786] = { 1322, 2879, 2, "INT", "crit", 3850, "haste", 3150, nil },
    [273787] = { 1322, 2879, 2, "SI", "crit", 3650, "versatility", 3350, nil },
    [273789] = { 1322, 2880, 3, "AI", "haste", 3750, "crit", 3250, nil },
    [273791] = { 1322, 2880, 3, "AI", "haste", 4000, "crit", 3000, nil },
    [273792] = { 1322, 2880, 3, nil, "haste", 11150, "crit", 6350, nil },
    [273793] = { 1322, 2878, 1, "AI", "mastery", 3900, "versatility", 3100, nil },
    [273794] = { 1322, 2879, 2, "INT", nil, nil, nil, nil, 1 },
    [273795] = { 1322, 2878, 1, "STR", nil, nil, nil, nil, 1 },
    [273796] = { 1322, 2878, 1, "SAI", nil, nil, nil, nil, 1 },
    [273797] = { 1322, 2880, 3, "SA", nil, nil, nil, nil, 1 },
    [275070] = { 1322, 2880, 3, "AGI", "crit", 4050, "haste", 2950, 1 },
}
