-- DodoInspect - tools/fixture_dungeonnames.lua
-- Generated by tools/gen_loot.py. Test fixture only: NOT part of the
-- addon, not in the TOC, excluded from the packaged zip.
--
-- UTF-8, unlike every other file this generator writes. That is the
-- point: it holds the official dungeon names as the client states them,
-- so tools/test_gearrank.lua can check that each hand-written Chinese
-- card label in Locales.lua really is a substring of one. Keyed by
-- journalInstanceID.

return {
    enUS = {
        [1030] = "Temple of Sethraliss",
        [1041] = "Kings' Rest",
        [1202] = "Ruby Life Pools",
        [1304] = "Murder Row",
        [1309] = "The Blinding Vale",
        [1311] = "Den of Nalorakk",
        [1313] = "Voidscar Arena",
        [1322] = "Altar of Fangs",
    },
    zhCN = {
        [1030] = "塞塔里斯神庙",
        [1041] = "诸王之眠",
        [1202] = "红玉新生法池",
        [1304] = "密谋小径",
        [1309] = "夺目谷",
        [1311] = "纳洛拉克的洞穴",
        [1313] = "虚空之痕竞技场",
        [1322] = "毒牙祭坛",
    },
}
