#!/usr/bin/env python3
# DodoInspect - tools/gen_loot.py
#
# Regenerates Data/Loot.lua from the live client DB2 tables published by
# wago.tools. Run once per season, or whenever the dungeon pool changes.
#
#   python tools/gen_loot.py            # writes ../Data/Loot.lua
#   python tools/gen_loot.py --dry-run  # prints a summary, writes nothing
#
# Pure stdlib, no third-party packages, no absolute paths. Output is ASCII
# only: item, boss and instance names are resolved in-game from the IDs, so
# the addon needs no translated strings of its own.

import argparse
import collections
import csv
import io
import os
import sys
import urllib.request

csv.field_size_limit(10 ** 7)

BASE = "https://wago.tools/db2/%s/csv"
UA = {"User-Agent": "DodoInspect-gen_loot/1.0"}

# Season 2 content. Raids show "#N BossName", dungeons show the instance
# name only, so the two groups are kept apart.
RAIDS = {
    1320: "The Venomous Abyss",
    1317: "The Tidebound Grotto",
}
DUNGEONS = {
    1322: "Altar of Fangs",
    1304: "Murder Row",
    1311: "Den of Nalorakk",
    1309: "The Blinding Vale",
    1313: "Voidscar Arena",
    1041: "Kings' Rest",
    1030: "Temple of Sethraliss",
    1202: "Ruby Life Pools",
}

# ItemSparse.StatModifier_bonusStat_N values we care about. The secondary
# keys match Data/StatPriority.lua exactly so the sort can compare them
# without a translation layer.
SECONDARY = {32: "crit", 36: "haste", 40: "versatility", 49: "mastery"}
PRIMARY = {3: "AGI", 4: "STR", 5: "INT",
           71: "SAI", 72: "SA", 73: "AI", 74: "SI"}

# The game writes "usable by more than one primary stat" two different
# ways: as a single hybrid stat id (74 = Strength-or-Intellect), or as two
# separate entries naming each stat. Reading only the first form is why
# every shield this season came out tagged Strength -- they use the second
# (STR:5259 + INT:16132), and taking the first entry dropped the Intellect
# half, hiding all six from holy paladins and restoration shamans.
#
# Fold by expanding each code to the stats it covers and mapping back.
PRIMARY_PARTS = {
    "STR": frozenset(("S",)),
    "AGI": frozenset(("A",)),
    "INT": frozenset(("I",)),
    "SA":  frozenset(("S", "A")),
    "AI":  frozenset(("A", "I")),
    "SI":  frozenset(("S", "I")),
    "SAI": frozenset(("S", "A", "I")),
}
PARTS_TO_PRIMARY = {parts: code for code, parts in PRIMARY_PARTS.items()}

# Armor subclass 5 is Cosmetic: transmog-only, item level 1, no stats.
COSMETIC_SUBCLASS = "5"
GEAR_CLASSES = ("2", "4")  # weapons, armor


# ChrSpecialization.PrimaryStatPriority is not a stat id, it is a scheme
# id. The mapping below is read off the live table and cross-checked
# against every hybrid class, which is what makes it trustworthy:
#   0 -> Intellect  priests, mages, warlocks, evokers, balance/resto
#                   druid, ele/resto shaman, mistweaver, DH Devourer
#   1 -> Intellect  holy paladin only, the one plate healer
#   2 -> Agility    hunters, enhancement shaman, brewmaster, windwalker
#   3 -> Agility    rogues, feral/guardian druid, havoc/vengeance DH
#   5 -> Strength   warriors, prot/ret paladin, all death knights
# Every hybrid splits correctly, which no single-class sample could show.
# 4 belongs to the non-player Adventurer spec and is filtered out.
STAT_SCHEME = {"0": "INT", "1": "INT", "2": "AGI", "3": "AGI", "5": "STR"}

# DB2 InventoryType -> the equipLoc string GetItemInfoInstant returns.
# Only used to build the offline test fixture; the addon itself asks the
# client. Coverage is asserted by the test, which requires every slot in
# SidePanel's SLOTS table to end up with candidates.
INVENTORY_TYPE = {
    1: "INVTYPE_HEAD", 2: "INVTYPE_NECK", 3: "INVTYPE_SHOULDER",
    4: "INVTYPE_BODY", 5: "INVTYPE_CHEST", 6: "INVTYPE_WAIST",
    7: "INVTYPE_LEGS", 8: "INVTYPE_FEET", 9: "INVTYPE_WRIST",
    10: "INVTYPE_HAND", 11: "INVTYPE_FINGER", 12: "INVTYPE_TRINKET",
    13: "INVTYPE_WEAPON", 14: "INVTYPE_SHIELD", 15: "INVTYPE_RANGED",
    16: "INVTYPE_CLOAK", 17: "INVTYPE_2HWEAPON", 19: "INVTYPE_TABARD",
    20: "INVTYPE_ROBE", 21: "INVTYPE_WEAPONMAINHAND",
    22: "INVTYPE_WEAPONOFFHAND", 23: "INVTYPE_HOLDABLE",
    25: "INVTYPE_THROWN", 26: "INVTYPE_RANGEDRIGHT", 28: "INVTYPE_RELIC",
}


def emit_fixture(source, items):
    """Offline stand-in for GetItemInfoInstant, built from the same Item
    rows the data file came from, so the test cannot drift from it."""
    lines = [
        "-- DodoInspect - tools/fixture_itemshape.lua\n",
        "-- Generated by tools/gen_loot.py. Test fixture only: this file\n",
        "-- is NOT part of the addon and is not listed in the TOC.\n",
        "--\n",
        "-- Real slot and armor data for every item in Data/Loot.lua, so\n",
        "-- the offline ranking test runs against the shapes the client\n",
        "-- would report rather than shapes hand-written to match the\n",
        "-- code's assumptions.\n\n",
        "return {\n",
    ]
    for item_id in sorted(source, key=int):
        item = items.get(item_id, {})
        equip = INVENTORY_TYPE.get(int(item.get("InventoryType") or 0))
        if not equip:
            continue
        lines.append('    [%s] = { "%s", %s, %s },\n'
                     % (item_id, equip, item.get("ClassID"),
                        item.get("SubclassID")))
    lines.append("}\n")
    return "".join(lines)
ARMOR_BY_ITEMTYPE = {1: "Cloth", 2: "Leather", 3: "Mail", 4: "Plate"}


def build_spec_gear():
    """specID -> (armor type, primary stat), derived, never hand-written."""
    specs = fetch("ChrSpecialization")
    item_specs = fetch("ItemSpec")

    armor = {}
    for row in item_specs:
        kind = int(row["ItemType"])
        if kind in ARMOR_BY_ITEMTYPE:
            armor.setdefault(row["SpecializationID"], set()).add(kind)

    out, problems = {}, []
    for spec in specs:
        kinds = armor.get(spec["ID"])
        # No armor entry at all means a non-player spec (Adventurer).
        # "Initial" is the pre-specialization placeholder every class has.
        if not kinds or spec["Name_lang"] == "Initial":
            continue
        if len(kinds) != 1:
            problems.append("spec %s maps to %d armor types"
                            % (spec["ID"], len(kinds)))
            continue
        primary = STAT_SCHEME.get(spec["PrimaryStatPriority"])
        if not primary:
            problems.append("spec %s has unmapped PrimaryStatPriority %r"
                            % (spec["ID"], spec["PrimaryStatPriority"]))
            continue
        out[int(spec["ID"])] = (ARMOR_BY_ITEMTYPE[kinds.pop()], primary,
                                spec["Name_lang"])
    return out, problems


# Weapon subclass -> the SkillLine that grants proficiency for it. Matched
# on SkillLine.DisplayName_lang rather than hardcoding line ids, so a
# renumbering cannot silently drop a weapon type. A RENAME still would,
# which is what the missing-line check below is for -- without it this
# whole table would just quietly shrink and every spec would look more
# restricted than it is.
WEAPON_SUBCLASS_SKILL_LINE = {
    0: "Axes", 1: "Two-Handed Axes", 2: "Bows", 3: "Guns",
    4: "Maces", 5: "Two-Handed Maces", 6: "Polearms", 7: "Swords",
    8: "Two-Handed Swords", 9: "Warglaives", 10: "Staves",
    13: "Fist Weapons", 15: "Daggers", 18: "Crossbows", 19: "Wands",
}
SHIELD_SKILL_LINE = "Shield"
CLASS_BITS = 13  # Warrior..Evoker; higher mask bits are not player classes


def build_spec_weapons(spec_gear):
    """specID -> weapon subclasses the spec's CLASS can equip, + shield use.

    Proficiency is a class fact and it is fully derivable: SkillLineAbility
    carries a ClassMask per weapon skill line. What is NOT derivable is
    INTENT -- a warrior can equip a one-hander and a shield, arms just
    should not -- so the handedness shape stays hand-written in GearRank.
    Keep the halves apart: this one must never be hand-edited, that one can
    never be generated.

    !! Do not try to answer "can this spec dual wield" from
    SpecializationSpells alone. Dual Wield is granted at TWO levels: class
    (SkillLineAbility spell 674, ClassMask 2573 = warrior/hunter/rogue/
    monk/demon hunter) and spec (frost death knight, enhancement shaman).
    Querying either source by itself returns a clean, confident, wrong
    answer -- the spec table reports "no" for every rogue.
    """
    lines = fetch("SkillLine")
    abilities = fetch("SkillLineAbility")
    specs = fetch("ChrSpecialization")

    line_id = {}
    for row in lines:
        name = (row.get("DisplayName_lang") or "").strip()
        if name:
            line_id.setdefault(name, row["ID"])

    mask_by_line = collections.defaultdict(int)
    for row in abilities:
        mask_by_line[row["SkillLine"]] |= int(row["ClassMask"])

    problems = []

    def classes_for(skill_name):
        lid = line_id.get(skill_name)
        if lid is None:
            problems.append("no SkillLine named %r (renamed?)" % skill_name)
            return set()
        mask = mask_by_line.get(lid, 0)
        if not mask:
            problems.append("skill line %r has no ClassMask" % skill_name)
            return set()
        return {c for c in range(1, CLASS_BITS + 1) if mask >> (c - 1) & 1}

    by_class = collections.defaultdict(set)
    for subclass, name in sorted(WEAPON_SUBCLASS_SKILL_LINE.items()):
        for class_id in classes_for(name):
            by_class[class_id].add(subclass)
    shield_classes = classes_for(SHIELD_SKILL_LINE)

    weapons, shields = {}, set()
    for spec in specs:
        spec_id = int(spec["ID"])
        if spec_id not in spec_gear:
            continue
        class_id = int(spec["ClassID"])
        if not by_class.get(class_id):
            problems.append("spec %d maps to class %d, which has no weapon "
                            "proficiency at all" % (spec_id, class_id))
            continue
        weapons[spec_id] = by_class[class_id]
        if class_id in shield_classes:
            shields.add(spec_id)

    # The two spec tables have to cover exactly the same specs, or some
    # spec gets an armor filter and no weapon filter (or the reverse) and
    # the panel silently changes behaviour for that one spec only.
    if set(weapons) != set(spec_gear):
        problems.append("SpecWeapons covers %d specs, SpecGear covers %d"
                        % (len(weapons), len(spec_gear)))
    return weapons, shields, problems


def fetch(table):
    req = urllib.request.Request(BASE % table, headers=UA)
    raw = urllib.request.urlopen(req).read().decode("utf-8")
    return list(csv.DictReader(io.StringIO(raw)))


def build_index():
    """Return (rows, meta) where rows maps itemID -> record."""
    encounters = fetch("JournalEncounter")
    drops = fetch("JournalEncounterItem")
    items = {r["ID"]: r for r in fetch("Item")}
    effects = {r["ItemID"] for r in fetch("ItemXItemEffect")}

    wanted = {str(i) for i in list(RAIDS) + list(DUNGEONS)}
    enc_meta = {}
    for e in encounters:
        if e.get("JournalInstanceID") in wanted:
            enc_meta[e["ID"]] = (e["JournalInstanceID"],
                                 int(e.get("OrderIndex") or 0))

    # itemID -> (instanceID, encounterID, orderIndex); keep the earliest
    # boss when an item is on several loot tables (only happens in the
    # returning dungeons, which never print a boss name anyway).
    source = {}
    multi = collections.Counter()
    for d in drops:
        meta = enc_meta.get(d["JournalEncounterID"])
        if not meta:
            continue
        item = items.get(d["ItemID"])
        if not item or item.get("ClassID") not in GEAR_CLASSES:
            continue
        if item.get("ClassID") == "4" and item.get("SubclassID") == COSMETIC_SUBCLASS:
            continue
        inst, order = meta
        prev = source.get(d["ItemID"])
        if prev:
            multi[d["ItemID"]] += 1
            if prev[2] <= order:
                continue
        source[d["ItemID"]] = (inst, d["JournalEncounterID"], order)

    # OrderIndex is not consistently based: the eight-boss raid runs 1..8
    # while the single-boss raid sits at 0, so printing it raw would give
    # "#0" and "#9". Renumber each instance onto a stable 1..N in
    # OrderIndex order, which is the order the Encounter Journal shows.
    per_instance = collections.defaultdict(set)
    for inst, order in enc_meta.values():
        per_instance[inst].add(order)
    rank = {}
    for inst, orders in per_instance.items():
        for position, order in enumerate(sorted(orders), start=1):
            rank[(inst, order)] = position
    source = {item: (inst, enc, rank[(inst, order)])
              for item, (inst, enc, order) in source.items()}

    return source, effects, multi, items


def read_stats(item_ids):
    """Stream ItemSparse (about 50 MB) and pull stats for item_ids only."""
    req = urllib.request.Request(BASE % "ItemSparse", headers=UA)
    stream = io.TextIOWrapper(urllib.request.urlopen(req), encoding="utf-8")
    reader = csv.DictReader(stream)
    out, multi_primary, unfoldable = {}, {}, {}
    for row in reader:
        if row["ID"] not in item_ids:
            continue
        primary, secondary, primaries = None, [], []
        for i in range(10):
            stat = int(row.get("StatModifier_bonusStat_%d" % i) or -1)
            amount = row.get("StatPercentEditor_%d" % i) or "0"
            if amount in ("0", "-1"):
                continue
            if stat in PRIMARY:
                primaries.append((PRIMARY[stat], int(amount)))
            elif stat in SECONDARY:
                secondary.append((SECONDARY[stat], int(amount)))

        # Two entries mean one of two opposite things, and telling them
        # apart is the whole job here:
        #   SAME stat twice   a scaling artefact on weapons and off-hands
        #                     (Int:5259 alongside Int:25370). First wins.
        #   DIFFERENT stats   the item is genuinely usable by both, written
        #                     out long-hand instead of as a hybrid id. Fold
        #                     them, or half its users lose the item.
        names = [name for name, _ in primaries]
        if not names:
            primary = None
        elif len(set(names)) == 1:
            primary = names[0]
        else:
            covered = frozenset().union(*(PRIMARY_PARTS[n] for n in names))
            primary = PARTS_TO_PRIMARY.get(covered)
            multi_primary[row["ID"]] = primaries
            if primary is None:
                unfoldable[row["ID"]] = names
        # Highest share first so the addon never has to sort a two-element
        # list at runtime.
        secondary.sort(key=lambda s: -s[1])
        out[row["ID"]] = (primary, secondary)
        if len(out) == len(item_ids):
            break
    return out, multi_primary, unfoldable


LUA_HEADER = '''-- DodoInspect - Data/Loot.lua
-- Season 2 loot tables, generated by tools/gen_loot.py. Do not hand-edit.
--
-- DATA ONLY, ASCII ONLY. Item, boss and instance names are resolved in
-- game from these IDs (C_Item.GetItemInfo / EJ_GetEncounterInfo /
-- EJ_GetInstanceInfo), so the table carries no translated strings and
-- every client language is covered for free.
--
-- Each entry is a positional array, keyed by itemID:
--   [1] journalInstanceID   [2] journalEncounterID
--   [3] boss position, 1..N in Encounter Journal order. This is NOT the
--       raw DB2 OrderIndex, which is 1-based in one raid and 0-based in
--       the other; the generator renumbers it.
--   [4] primary stat        "STR" "AGI" "INT" "SI" "SA" "AI" "SAI",
--                           or nil for rings and necks, which have none
--   [5] first secondary     stat key, matching Data/StatPriority.lua
--   [6] first secondary value
--   [7] second secondary    nil when the item puts everything in one stat
--   [8] second secondary value
--   [9] 1 when the item carries an on-item effect (cantrip, use effect,
--       proc). Those carry value the stat sort cannot see, so the panel
--       flags them rather than pretending the order is complete.
--
-- Secondary values do NOT share a budget across slots: armor totals about
-- 7000, rings and necks about 17500. Normalise against the item's own
-- total ([6] + [8]), never against a constant.
--
-- Slot and armor type are deliberately absent: GetItemInfoInstant returns
-- them synchronously without needing the item cached.

local _, ns = ...

'''


def emit(source, stats, effects, build, today, spec_gear,
         spec_weapons, spec_shields):
    lines = [LUA_HEADER]

    lines.append("-- specID -> armor type and primary stat, derived from\n")
    lines.append("-- ChrSpecialization and ItemSpec. Used to filter the\n")
    lines.append("-- candidate list: a plate wearer must not be shown the\n")
    lines.append("-- other plate classes' gear, which armor type alone\n")
    lines.append("-- does not achieve (holy paladin wants Intellect while\n")
    lines.append("-- every warrior wants Strength). Rings, necks and cloaks\n")
    lines.append("-- carry no primary stat and skip this filter entirely.\n")
    lines.append("ns.SpecGear = {\n")
    for spec_id in sorted(spec_gear):
        armor, primary, name = spec_gear[spec_id]
        lines.append('    [%d] = { "%s", "%s" }, -- %s\n'
                     % (spec_id, armor, primary, name))
    lines.append("}\n\n")

    lines.append("-- specID -> the weapon subclass ids that spec's CLASS is\n")
    lines.append("-- allowed to equip, derived from SkillLine +\n")
    lines.append("-- SkillLineAbility.ClassMask. This answers CAN, never\n")
    lines.append("-- SHOULD: a warrior appears here with daggers and bows.\n")
    lines.append("-- Which of them a spec actually wants is the hand-written\n")
    lines.append("-- weapon shape in GearRank.lua. Subclass ids are Blizzard's\n")
    lines.append("-- (0 axe, 1 2h-axe, 2 bow, 3 gun, 4 mace, 5 2h-mace,\n")
    lines.append("--  6 polearm, 7 sword, 8 2h-sword, 9 warglaive, 10 staff,\n")
    lines.append("--  13 fist, 15 dagger, 18 crossbow, 19 wand).\n")
    lines.append("ns.SpecWeapons = {\n")
    for spec_id in sorted(spec_weapons):
        subs = sorted(spec_weapons[spec_id])
        name = spec_gear[spec_id][2]
        lines.append("    [%d] = { %s }, -- %s\n"
                     % (spec_id,
                        ", ".join("[%d] = true" % s for s in subs), name))
    lines.append("}\n\n")

    lines.append("-- specIDs whose class has shield proficiency. Separate\n")
    lines.append("-- from the table above because a shield is armor, not a\n")
    lines.append("-- weapon subclass, and the off-hand pool needs both.\n")
    lines.append("ns.SpecShield = {\n")
    for spec_id in sorted(spec_shields):
        lines.append("    [%d] = true, -- %s\n"
                     % (spec_id, spec_gear[spec_id][2]))
    lines.append("}\n\n")

    lines.append("ns.LootMeta = {\n")
    lines.append('    build = "%s",\n' % build)
    lines.append('    date = "%s",\n' % today)
    lines.append("    raids = { %s },\n"
                 % ", ".join("[%d] = true" % i for i in sorted(RAIDS)))
    lines.append("    dungeons = { %s },\n"
                 % ", ".join("[%d] = true" % i for i in sorted(DUNGEONS)))
    lines.append("}\n\nns.LootData = {\n")

    by_inst = collections.defaultdict(list)
    for item_id, (inst, enc, order) in source.items():
        by_inst[int(inst)].append((int(item_id), enc, order))

    names = dict(RAIDS)
    names.update(DUNGEONS)
    for inst in sorted(by_inst, key=lambda i: (i not in RAIDS, i)):
        lines.append("\n    -- %s\n" % names[inst])
        for item_id, enc, order in sorted(by_inst[inst]):
            primary, secondary = stats.get(str(item_id), (None, []))
            parts = [str(inst), enc, str(order)]
            parts.append('"%s"' % primary if primary else "nil")
            for slot in range(2):
                if slot < len(secondary):
                    parts.append('"%s"' % secondary[slot][0])
                    parts.append(str(secondary[slot][1]))
                else:
                    parts.extend(["nil", "nil"])
            parts.append("1" if str(item_id) in effects else "nil")
            lines.append("    [%d] = { %s },\n" % (item_id, ", ".join(parts)))
    lines.append("}\n")
    return "".join(lines)


def live_build():
    import json
    req = urllib.request.Request("https://wago.tools/api/builds", headers=UA)
    data = json.loads(urllib.request.urlopen(req).read().decode("utf-8"))
    return data["wow"][0]["version"]


def main():
    import datetime
    parser = argparse.ArgumentParser(description="Regenerate Data/Loot.lua")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the summary without writing the file")
    args = parser.parse_args()

    build = live_build()
    print("live client build: %s" % build)

    source, effects, multi, items = build_index()
    print("gear items: %d" % len(source))
    if multi:
        print("items on more than one loot table: %d (earliest boss kept)"
              % len(multi))

    stats, multi_primary, unfoldable = read_stats(set(source))

    # This check used to read "armor must never carry a second primary-stat
    # entry", scoped to ClassID 4 with SubclassID 1-4. That scope WAS the
    # bug: shields are SubclassID 6, so they sat outside it and quietly took
    # the weapon treatment -- first entry wins -- which tagged all six of
    # this season's Strength-or-Intellect shields as Strength and hid them
    # from every Intellect user. The guard was right; its reach was not.
    #
    # The rule is now "every multi-entry item must fold into a known primary
    # code", which needs no scope at all: it covers armor, shields, weapons
    # and anything the next season invents.
    if unfoldable:
        print("ERROR: %d items have primary-stat entries that do not fold "
              "into a known code, so their primary stat is unknown rather "
              "than merely approximate: %s"
              % (len(unfoldable), list(unfoldable.items())[:6]),
              file=sys.stderr)
        return 1
    print("items usable by more than one primary stat (folded): %d"
          % len(multi_primary))

    missing = [i for i in source if i not in stats]
    if missing:
        print("WARNING: no ItemSparse row for %d items: %s"
              % (len(missing), missing[:8]), file=sys.stderr)

    # Items without secondary stats fall into three very different buckets
    # and only one of them is a problem, so report them apart. Trinkets
    # legitimately have none; the armor cases are Battle for Azeroth
    # azerite head/shoulder/chest, which predate secondary stats entirely.
    ARMOR_SUBCLASSES = ("1", "2", "3", "4")
    buckets = collections.Counter()
    for item_id, (_, secondary) in stats.items():
        if secondary:
            continue
        item = items.get(item_id, {})
        if item.get("ClassID") == "2":
            buckets["weapon"] += 1
        elif item.get("SubclassID") in ARMOR_SUBCLASSES:
            buckets["armor"] += 1
        else:
            buckets["trinket or accessory"] += 1
    for bucket, count in sorted(buckets.items()):
        note = " <- these cannot be ranked by stats" if bucket == "armor" else ""
        print("no secondary stats, %s: %d%s" % (bucket, count, note))

    spec_gear, spec_problems = build_spec_gear()
    for problem in spec_problems:
        print("ERROR: %s" % problem, file=sys.stderr)
    if spec_problems:
        return 1
    # The live game has 40 player specs. Fewer means the filter above ate
    # something real and some spec would silently get an empty panel.
    print("player specs mapped: %d" % len(spec_gear))
    if len(spec_gear) < 40:
        print("ERROR: expected at least 40 player specs, got %d"
              % len(spec_gear), file=sys.stderr)
        return 1

    spec_weapons, spec_shields, weapon_problems = build_spec_weapons(spec_gear)
    for problem in weapon_problems:
        print("ERROR: %s" % problem, file=sys.stderr)
    if weapon_problems:
        return 1
    # Two sanity anchors on the derived proficiency table. They are cheap
    # and they fail loudly: without them a renamed skill line would just
    # shrink everyone's weapon list, which reads like a stricter filter
    # rather than like broken data.
    #   rogue subtlety (261) must NOT have staves (10)
    #   demon hunter havoc (577) MUST have warglaives (9)
    if 10 in spec_weapons.get(261, ()):
        print("ERROR: derived proficiency gives rogues staves", file=sys.stderr)
        return 1
    if 9 not in spec_weapons.get(577, ()):
        print("ERROR: derived proficiency denies demon hunters warglaives",
              file=sys.stderr)
        return 1
    print("weapon proficiency derived for %d specs, %d can use shields"
          % (len(spec_weapons), len(spec_shields)))

    today = datetime.date.today().isoformat()
    text = emit(source, stats, effects, build, today, spec_gear,
                spec_weapons, spec_shields)

    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, os.pardir, "Data", "Loot.lua")
    if args.dry_run:
        print("dry run: would write %d bytes to %s"
              % (len(text), os.path.normpath(target)))
        return

    with open(target, "w", encoding="ascii", newline="\n") as handle:
        handle.write(text)
    print("wrote %s (%d bytes, %d items, %d with effects)"
          % (os.path.normpath(target), len(text), len(source),
             len(effects & set(source))))

    fixture = os.path.join(here, "fixture_itemshape.lua")
    fixture_text = emit_fixture(source, items)
    with open(fixture, "w", encoding="ascii", newline="\n") as handle:
        handle.write(fixture_text)
    print("wrote %s (test fixture, not shipped)" % os.path.normpath(fixture))


if __name__ == "__main__":
    # sys.exit, not a bare call: every guard in main() reports by
    # returning 1, and a bare main() throws that away -- the
    # process exited 0 even when it refused to write the file.
    sys.exit(main())
