#!/usr/bin/env python3
# DodoInspect - tools/gen_loot.py
#
# Regenerates Data/Loot.lua from the live client DB2 tables published by
# wago.tools. Run once per season, or whenever the dungeon pool changes.
#
#   python tools/gen_loot.py            # writes ../Data/Loot.lua
#   python tools/gen_loot.py --dry-run  # prints a summary, writes nothing
#
# Pure stdlib, no third-party packages, no absolute paths. Output is ASCII
# only: item, boss and instance names are resolved in-game from the IDs, so
# the addon needs no translated strings of its own.

import argparse
import collections
import csv
import io
import os
import sys
import urllib.request

csv.field_size_limit(10 ** 7)

BASE = "https://wago.tools/db2/%s/csv"
UA = {"User-Agent": "DodoInspect-gen_loot/1.0"}

# Season 2 content. Raids show "#N BossName", dungeons show the instance
# name only, so the two groups are kept apart.
RAIDS = {
    1320: "The Venomous Abyss",
    1317: "The Tidebound Grotto",
}
DUNGEONS = {
    1322: "Altar of Fangs",
    1304: "Murder Row",
    1311: "Den of Nalorakk",
    1309: "The Blinding Vale",
    1313: "Voidscar Arena",
    1041: "Kings' Rest",
    1030: "Temple of Sethraliss",
    1202: "Ruby Life Pools",
}

# ItemSparse.StatModifier_bonusStat_N values we care about. The secondary
# keys match Data/StatPriority.lua exactly so the sort can compare them
# without a translation layer.
SECONDARY = {32: "crit", 36: "haste", 40: "versatility", 49: "mastery"}
PRIMARY = {3: "AGI", 4: "STR", 5: "INT",
           71: "SAI", 72: "SA", 73: "AI", 74: "SI"}

# Armor subclass 5 is Cosmetic: transmog-only, item level 1, no stats.
COSMETIC_SUBCLASS = "5"
GEAR_CLASSES = ("2", "4")  # weapons, armor


# ChrSpecialization.PrimaryStatPriority is not a stat id, it is a scheme
# id. The mapping below is read off the live table and cross-checked
# against every hybrid class, which is what makes it trustworthy:
#   0 -> Intellect  priests, mages, warlocks, evokers, balance/resto
#                   druid, ele/resto shaman, mistweaver, DH Devourer
#   1 -> Intellect  holy paladin only, the one plate healer
#   2 -> Agility    hunters, enhancement shaman, brewmaster, windwalker
#   3 -> Agility    rogues, feral/guardian druid, havoc/vengeance DH
#   5 -> Strength   warriors, prot/ret paladin, all death knights
# Every hybrid splits correctly, which no single-class sample could show.
# 4 belongs to the non-player Adventurer spec and is filtered out.
STAT_SCHEME = {"0": "INT", "1": "INT", "2": "AGI", "3": "AGI", "5": "STR"}

# DB2 InventoryType -> the equipLoc string GetItemInfoInstant returns.
# Only used to build the offline test fixture; the addon itself asks the
# client. Coverage is asserted by the test, which requires every slot in
# SidePanel's SLOTS table to end up with candidates.
INVENTORY_TYPE = {
    1: "INVTYPE_HEAD", 2: "INVTYPE_NECK", 3: "INVTYPE_SHOULDER",
    4: "INVTYPE_BODY", 5: "INVTYPE_CHEST", 6: "INVTYPE_WAIST",
    7: "INVTYPE_LEGS", 8: "INVTYPE_FEET", 9: "INVTYPE_WRIST",
    10: "INVTYPE_HAND", 11: "INVTYPE_FINGER", 12: "INVTYPE_TRINKET",
    13: "INVTYPE_WEAPON", 14: "INVTYPE_SHIELD", 15: "INVTYPE_RANGED",
    16: "INVTYPE_CLOAK", 17: "INVTYPE_2HWEAPON", 19: "INVTYPE_TABARD",
    20: "INVTYPE_ROBE", 21: "INVTYPE_WEAPONMAINHAND",
    22: "INVTYPE_WEAPONOFFHAND", 23: "INVTYPE_HOLDABLE",
    25: "INVTYPE_THROWN", 26: "INVTYPE_RANGEDRIGHT", 28: "INVTYPE_RELIC",
}


def emit_fixture(source, items):
    """Offline stand-in for GetItemInfoInstant, built from the same Item
    rows the data file came from, so the test cannot drift from it."""
    lines = [
        "-- DodoInspect - tools/fixture_itemshape.lua\n",
        "-- Generated by tools/gen_loot.py. Test fixture only: this file\n",
        "-- is NOT part of the addon and is not listed in the TOC.\n",
        "--\n",
        "-- Real slot and armor data for every item in Data/Loot.lua, so\n",
        "-- the offline ranking test runs against the shapes the client\n",
        "-- would report rather than shapes hand-written to match the\n",
        "-- code's assumptions.\n\n",
        "return {\n",
    ]
    for item_id in sorted(source, key=int):
        item = items.get(item_id, {})
        equip = INVENTORY_TYPE.get(int(item.get("InventoryType") or 0))
        if not equip:
            continue
        lines.append('    [%s] = { "%s", %s, %s },\n'
                     % (item_id, equip, item.get("ClassID"),
                        item.get("SubclassID")))
    lines.append("}\n")
    return "".join(lines)
ARMOR_BY_ITEMTYPE = {1: "Cloth", 2: "Leather", 3: "Mail", 4: "Plate"}


def build_spec_gear():
    """specID -> (armor type, primary stat), derived, never hand-written."""
    specs = fetch("ChrSpecialization")
    item_specs = fetch("ItemSpec")

    armor = {}
    for row in item_specs:
        kind = int(row["ItemType"])
        if kind in ARMOR_BY_ITEMTYPE:
            armor.setdefault(row["SpecializationID"], set()).add(kind)

    out, problems = {}, []
    for spec in specs:
        kinds = armor.get(spec["ID"])
        # No armor entry at all means a non-player spec (Adventurer).
        # "Initial" is the pre-specialization placeholder every class has.
        if not kinds or spec["Name_lang"] == "Initial":
            continue
        if len(kinds) != 1:
            problems.append("spec %s maps to %d armor types"
                            % (spec["ID"], len(kinds)))
            continue
        primary = STAT_SCHEME.get(spec["PrimaryStatPriority"])
        if not primary:
            problems.append("spec %s has unmapped PrimaryStatPriority %r"
                            % (spec["ID"], spec["PrimaryStatPriority"]))
            continue
        out[int(spec["ID"])] = (ARMOR_BY_ITEMTYPE[kinds.pop()], primary,
                                spec["Name_lang"])
    return out, problems


def fetch(table):
    req = urllib.request.Request(BASE % table, headers=UA)
    raw = urllib.request.urlopen(req).read().decode("utf-8")
    return list(csv.DictReader(io.StringIO(raw)))


def build_index():
    """Return (rows, meta) where rows maps itemID -> record."""
    encounters = fetch("JournalEncounter")
    drops = fetch("JournalEncounterItem")
    items = {r["ID"]: r for r in fetch("Item")}
    effects = {r["ItemID"] for r in fetch("ItemXItemEffect")}

    wanted = {str(i) for i in list(RAIDS) + list(DUNGEONS)}
    enc_meta = {}
    for e in encounters:
        if e.get("JournalInstanceID") in wanted:
            enc_meta[e["ID"]] = (e["JournalInstanceID"],
                                 int(e.get("OrderIndex") or 0))

    # itemID -> (instanceID, encounterID, orderIndex); keep the earliest
    # boss when an item is on several loot tables (only happens in the
    # returning dungeons, which never print a boss name anyway).
    source = {}
    multi = collections.Counter()
    for d in drops:
        meta = enc_meta.get(d["JournalEncounterID"])
        if not meta:
            continue
        item = items.get(d["ItemID"])
        if not item or item.get("ClassID") not in GEAR_CLASSES:
            continue
        if item.get("ClassID") == "4" and item.get("SubclassID") == COSMETIC_SUBCLASS:
            continue
        inst, order = meta
        prev = source.get(d["ItemID"])
        if prev:
            multi[d["ItemID"]] += 1
            if prev[2] <= order:
                continue
        source[d["ItemID"]] = (inst, d["JournalEncounterID"], order)

    # OrderIndex is not consistently based: the eight-boss raid runs 1..8
    # while the single-boss raid sits at 0, so printing it raw would give
    # "#0" and "#9". Renumber each instance onto a stable 1..N in
    # OrderIndex order, which is the order the Encounter Journal shows.
    per_instance = collections.defaultdict(set)
    for inst, order in enc_meta.values():
        per_instance[inst].add(order)
    rank = {}
    for inst, orders in per_instance.items():
        for position, order in enumerate(sorted(orders), start=1):
            rank[(inst, order)] = position
    source = {item: (inst, enc, rank[(inst, order)])
              for item, (inst, enc, order) in source.items()}

    return source, effects, multi, items


def read_stats(item_ids):
    """Stream ItemSparse (about 50 MB) and pull stats for item_ids only."""
    req = urllib.request.Request(BASE % "ItemSparse", headers=UA)
    stream = io.TextIOWrapper(urllib.request.urlopen(req), encoding="utf-8")
    reader = csv.DictReader(stream)
    out, multi_primary = {}, {}
    for row in reader:
        if row["ID"] not in item_ids:
            continue
        primary, secondary, primaries = None, [], []
        for i in range(10):
            stat = int(row.get("StatModifier_bonusStat_%d" % i) or -1)
            amount = row.get("StatPercentEditor_%d" % i) or "0"
            if amount in ("0", "-1"):
                continue
            if stat in PRIMARY:
                # Weapons and off-hands carry a second, much larger entry
                # in this array on top of the real primary stat. The first
                # one is the primary stat; later ones are not.
                primaries.append((PRIMARY[stat], int(amount)))
                if primary is None:
                    primary = PRIMARY[stat]
            elif stat in SECONDARY:
                secondary.append((SECONDARY[stat], int(amount)))
        if len(primaries) > 1:
            multi_primary[row["ID"]] = primaries
        # Highest share first so the addon never has to sort a two-element
        # list at runtime.
        secondary.sort(key=lambda s: -s[1])
        out[row["ID"]] = (primary, secondary)
        if len(out) == len(item_ids):
            break
    return out, multi_primary


LUA_HEADER = '''-- DodoInspect - Data/Loot.lua
-- Season 2 loot tables, generated by tools/gen_loot.py. Do not hand-edit.
--
-- DATA ONLY, ASCII ONLY. Item, boss and instance names are resolved in
-- game from these IDs (C_Item.GetItemInfo / EJ_GetEncounterInfo /
-- EJ_GetInstanceInfo), so the table carries no translated strings and
-- every client language is covered for free.
--
-- Each entry is a positional array, keyed by itemID:
--   [1] journalInstanceID   [2] journalEncounterID
--   [3] boss position, 1..N in Encounter Journal order. This is NOT the
--       raw DB2 OrderIndex, which is 1-based in one raid and 0-based in
--       the other; the generator renumbers it.
--   [4] primary stat        "STR" "AGI" "INT" "SI" "SA" "AI" "SAI",
--                           or nil for rings and necks, which have none
--   [5] first secondary     stat key, matching Data/StatPriority.lua
--   [6] first secondary value
--   [7] second secondary    nil when the item puts everything in one stat
--   [8] second secondary value
--   [9] 1 when the item carries an on-item effect (cantrip, use effect,
--       proc). Those carry value the stat sort cannot see, so the panel
--       flags them rather than pretending the order is complete.
--
-- Secondary values do NOT share a budget across slots: armor totals about
-- 7000, rings and necks about 17500. Normalise against the item's own
-- total ([6] + [8]), never against a constant.
--
-- Slot and armor type are deliberately absent: GetItemInfoInstant returns
-- them synchronously without needing the item cached.

local _, ns = ...

'''


def emit(source, stats, effects, build, today, spec_gear):
    lines = [LUA_HEADER]

    lines.append("-- specID -> armor type and primary stat, derived from\n")
    lines.append("-- ChrSpecialization and ItemSpec. Used to filter the\n")
    lines.append("-- candidate list: a plate wearer must not be shown the\n")
    lines.append("-- other plate classes' gear, which armor type alone\n")
    lines.append("-- does not achieve (holy paladin wants Intellect while\n")
    lines.append("-- every warrior wants Strength). Rings, necks and cloaks\n")
    lines.append("-- carry no primary stat and skip this filter entirely.\n")
    lines.append("ns.SpecGear = {\n")
    for spec_id in sorted(spec_gear):
        armor, primary, name = spec_gear[spec_id]
        lines.append('    [%d] = { "%s", "%s" }, -- %s\n'
                     % (spec_id, armor, primary, name))
    lines.append("}\n\n")

    lines.append("ns.LootMeta = {\n")
    lines.append('    build = "%s",\n' % build)
    lines.append('    date = "%s",\n' % today)
    lines.append("    raids = { %s },\n"
                 % ", ".join("[%d] = true" % i for i in sorted(RAIDS)))
    lines.append("    dungeons = { %s },\n"
                 % ", ".join("[%d] = true" % i for i in sorted(DUNGEONS)))
    lines.append("}\n\nns.LootData = {\n")

    by_inst = collections.defaultdict(list)
    for item_id, (inst, enc, order) in source.items():
        by_inst[int(inst)].append((int(item_id), enc, order))

    names = dict(RAIDS)
    names.update(DUNGEONS)
    for inst in sorted(by_inst, key=lambda i: (i not in RAIDS, i)):
        lines.append("\n    -- %s\n" % names[inst])
        for item_id, enc, order in sorted(by_inst[inst]):
            primary, secondary = stats.get(str(item_id), (None, []))
            parts = [str(inst), enc, str(order)]
            parts.append('"%s"' % primary if primary else "nil")
            for slot in range(2):
                if slot < len(secondary):
                    parts.append('"%s"' % secondary[slot][0])
                    parts.append(str(secondary[slot][1]))
                else:
                    parts.extend(["nil", "nil"])
            parts.append("1" if str(item_id) in effects else "nil")
            lines.append("    [%d] = { %s },\n" % (item_id, ", ".join(parts)))
    lines.append("}\n")
    return "".join(lines)


def live_build():
    import json
    req = urllib.request.Request("https://wago.tools/api/builds", headers=UA)
    data = json.loads(urllib.request.urlopen(req).read().decode("utf-8"))
    return data["wow"][0]["version"]


def main():
    import datetime
    parser = argparse.ArgumentParser(description="Regenerate Data/Loot.lua")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the summary without writing the file")
    args = parser.parse_args()

    build = live_build()
    print("live client build: %s" % build)

    source, effects, multi, items = build_index()
    print("gear items: %d" % len(source))
    if multi:
        print("items on more than one loot table: %d (earliest boss kept)"
              % len(multi))

    stats, multi_primary = read_stats(set(source))

    # The "first entry wins" rule above is only safe because armor never
    # carries a second primary-stat entry. Assert it rather than trust it:
    # if that ever changes, armor primary stats silently become wrong and
    # the panel starts showing plate wearers each other's gear.
    armor_multi = [i for i in multi_primary
                   if items.get(i, {}).get("SubclassID") in ("1", "2", "3", "4")
                   and items.get(i, {}).get("ClassID") == "4"]
    if armor_multi:
        print("ERROR: %d armor pieces have more than one primary stat entry, "
              "so the primary stat filter cannot be trusted: %s"
              % (len(armor_multi), armor_multi[:8]), file=sys.stderr)
        return 1
    print("multiple primary-stat entries (weapons and off-hands only): %d"
          % len(multi_primary))

    missing = [i for i in source if i not in stats]
    if missing:
        print("WARNING: no ItemSparse row for %d items: %s"
              % (len(missing), missing[:8]), file=sys.stderr)

    # Items without secondary stats fall into three very different buckets
    # and only one of them is a problem, so report them apart. Trinkets
    # legitimately have none; the armor cases are Battle for Azeroth
    # azerite head/shoulder/chest, which predate secondary stats entirely.
    ARMOR_SUBCLASSES = ("1", "2", "3", "4")
    buckets = collections.Counter()
    for item_id, (_, secondary) in stats.items():
        if secondary:
            continue
        item = items.get(item_id, {})
        if item.get("ClassID") == "2":
            buckets["weapon"] += 1
        elif item.get("SubclassID") in ARMOR_SUBCLASSES:
            buckets["armor"] += 1
        else:
            buckets["trinket or accessory"] += 1
    for bucket, count in sorted(buckets.items()):
        note = " <- these cannot be ranked by stats" if bucket == "armor" else ""
        print("no secondary stats, %s: %d%s" % (bucket, count, note))

    spec_gear, spec_problems = build_spec_gear()
    for problem in spec_problems:
        print("ERROR: %s" % problem, file=sys.stderr)
    if spec_problems:
        return 1
    # The live game has 40 player specs. Fewer means the filter above ate
    # something real and some spec would silently get an empty panel.
    print("player specs mapped: %d" % len(spec_gear))
    if len(spec_gear) < 40:
        print("ERROR: expected at least 40 player specs, got %d"
              % len(spec_gear), file=sys.stderr)
        return 1

    today = datetime.date.today().isoformat()
    text = emit(source, stats, effects, build, today, spec_gear)

    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, os.pardir, "Data", "Loot.lua")
    if args.dry_run:
        print("dry run: would write %d bytes to %s"
              % (len(text), os.path.normpath(target)))
        return

    with open(target, "w", encoding="ascii", newline="\n") as handle:
        handle.write(text)
    print("wrote %s (%d bytes, %d items, %d with effects)"
          % (os.path.normpath(target), len(text), len(source),
             len(effects & set(source))))

    fixture = os.path.join(here, "fixture_itemshape.lua")
    fixture_text = emit_fixture(source, items)
    with open(fixture, "w", encoding="ascii", newline="\n") as handle:
        handle.write(fixture_text)
    print("wrote %s (test fixture, not shipped)" % os.path.normpath(fixture))


if __name__ == "__main__":
    main()
